#
# Development environment services
# DO NOT USE FOR PRODUCTION
#

app:
  build: .
  command: gunicorn --paster develop.ini
  restart: always
  ports:
    - "3000:3000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./occams_studies:/app/occams_studies
    - ./develop.ini:/app/develop.ini
    - ./tests:/app/tests
    - occams_uploads:/files/uploads
    - occams_exports:/files/exports

celery:
  build: .
  command: celery worker --autoreload --app occams --loglevel INFO --without-gossip --ini develop.ini
  restart: always
  environment:
    - C_FORCE_ROOT=1
  links:
    - postgres:postgres
    - redis:redis
  volumes_from:
    - app

postgres:
  image: postgres:9.5
  restart: always
  environment:
    - POSTGRES_USER=occams
    - POSTGRES_DB=occams
  ports:
    - "5432:5432"
  volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - occams_db:/var/lib/postgresql/data/

redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
